site_name: CodeCAD
site_description: Parametric CAD with Lua – fast, simple, frictionless.
site_url: https://codecad.xyz
repo_url: https://github.com/breiting/codecad
repo_name: breiting/codecad

copyright: Bernhard Reitinger © 2025
site_author: Bernhard Reitinger

site_description: |
 CodeCAD is a parametric CAD with Lua.

nav:
  - Introduction: introduction.md
  - Installation: installation.md
  - Getting Started: getting_started.md
  # - API Reference: api/index.md
  # - Tutorials: tutorials/index.md

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  # logo: 'assets/images/chekker-logo.png'
  favicon: 'assets/images/favicon.png'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
