site_name: CodeCAD
site_description: Parametric CAD with Lua – fast, simple, frictionless.
site_url: https://codecad.xyz
repo_url: https://github.com/breiting/codecad
repo_name: breiting/codecad

copyright: Bernhard Reitinger © 2025
site_author: Bernhard Reitinger

site_description: "CodeCAD is a lightweight parametric modeling toolkit powered by Lua and OpenCascade – simple, scriptable, and perfect for makers & engineers."

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Getting Started: getting_started.md
  - Design Principles: design_principles.md
  - CodeCAD in Practice: in_practice.md
  - Core Functionality:
      - Primitives: core_primitives.md
      - Boolean: core_boolean.md
      - Transformation: core_transform.md
      - Features: core_features.md
      - Sketches: core_sketches.md
      - Construction: core_construction.md
      - Mechanical: core_mechanical.md
  - Terminology: terminology.md

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.expand
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  logo: 'images/CodeCAD-logo.png'
  favicon: 'images/favicon.ico'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - toc:
      permalink: true

extra_javascript:
  - assets/js/stl-viewer-bootstrap.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/viewer.css

